# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9a339ac6e4b7070ccfb6e6ac8247d7f1"
name = "checkout-guarantee-message"
handle = "checkout-guarantee-message"
application_url = "https://carolina-hansen-hint-previous.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dev-sunnies-studios.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://carolina-hansen-hint-previous.trycloudflare.com/auth/callback",
  "https://carolina-hansen-hint-previous.trycloudflare.com/auth/shopify/callback",
  "https://carolina-hansen-hint-previous.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
